version: '3'

volumes:
  storage:

services:
  reviews:
    build: .
    depends_on:
      - 'postgres'
    ports:
      - '3002:3002'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'root'
    volumes:
      - 'storage:/data/db'